<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.5">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kush Desai">
<meta name="dcterms.date" content="2025-04-19">

<title>A Replication of Karlan and List (2007) – Kush’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ff4371ef257df69894857e99c6ad0d06.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fad75ad56f58d7d7495cdbca50e3d220.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Kush’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  <li><a href="#unconditional-analysis" id="toc-unconditional-analysis" class="nav-link" data-scroll-target="#unconditional-analysis">Unconditional Analysis</a></li>
  <li><a href="#conditional-on-giving" id="toc-conditional-on-giving" class="nav-link" data-scroll-target="#conditional-on-giving">Conditional on Giving</a></li>
  <li><a href="#visual-comparison" id="toc-visual-comparison" class="nav-link" data-scroll-target="#visual-comparison">Visual Comparison</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kush Desai </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 19, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>The experiment randomly assigned individuals to receive either a standard fundraising letter or one that included a matching grant offer at different match ratios: $1:$1, $2:$1, or $3:$1. Some letters also varied the maximum amount that would be matched ($25,000, $50,000, $100,000, or unstated) and included different suggested donation amounts based on the recipient’s previous giving history. The researchers then tracked donation response rates and amounts to evaluate how price framing and match incentives affected giving behavior. This design allowed them to isolate the impact of price-based incentives while preserving the realism of a natural fundraising campaign.</p>
<p>This project seeks to replicate their results.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<div id="b0bd1a17" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get dataset dimensions</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>data_shape <span class="op">=</span> data.shape</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview first few rows</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>data_head <span class="op">=</span> data.head()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean summary of non-null counts and data types</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>data_summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Column'</span>: data.columns,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Non-Null Count'</span>: data.notnull().<span class="bu">sum</span>().values,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Dtype'</span>: data.dtypes.values</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic descriptive statistics for numeric columns</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>data_description <span class="op">=</span> data.describe()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display all in order</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>data_shape, data_summary.head, data_description</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>((50083, 51),
 &lt;bound method NDFrame.head of                 Column  Non-Null Count     Dtype
 0            treatment           50083      int8
 1              control           50083      int8
 2                ratio           50083  category
 3               ratio2           50083      int8
 4               ratio3           50083      int8
 5                 size           50083  category
 6               size25           50083      int8
 7               size50           50083      int8
 8              size100           50083      int8
 9               sizeno           50083      int8
 10                 ask           50083  category
 11               askd1           50083      int8
 12               askd2           50083      int8
 13               askd3           50083      int8
 14                ask1           50083     int16
 15                ask2           50083     int16
 16                ask3           50083     int16
 17              amount           50083   float32
 18                gave           50083      int8
 19        amountchange           50083   float32
 20                 hpa           50083   float32
 21            ltmedmra           50083      int8
 22                freq           50083     int16
 23               years           50082   float64
 24               year5           50083      int8
 25                mrm2           50082   float64
 26             dormant           50083      int8
 27              female           48972   float64
 28              couple           48935   float64
 29          state50one           50083      int8
 30              nonlit           49631   float64
 31               cases           49631   float64
 32            statecnt           50083   float32
 33       stateresponse           50083   float32
 34      stateresponset           50083   float32
 35      stateresponsec           50080   float32
 36  stateresponsetminc           50080   float32
 37             perbush           50048   float32
 38             close25           50048   float64
 39                red0           50048   float64
 40               blue0           50048   float64
 41              redcty           49978   float64
 42             bluecty           49978   float64
 43              pwhite           48217   float32
 44              pblack           48047   float32
 45           page18_39           48217   float32
 46           ave_hh_sz           48221   float32
 47     median_hhincome           48209   float64
 48              powner           48214   float32
 49        psch_atlstba           48215   float32
 50       pop_propurban           48217   float32&gt;,
           treatment       control        ratio2        ratio3        size25  \
 count  50083.000000  50083.000000  50083.000000  50083.000000  50083.000000   
 mean       0.666813      0.333187      0.222311      0.222211      0.166723   
 std        0.471357      0.471357      0.415803      0.415736      0.372732   
 min        0.000000      0.000000      0.000000      0.000000      0.000000   
 25%        0.000000      0.000000      0.000000      0.000000      0.000000   
 50%        1.000000      0.000000      0.000000      0.000000      0.000000   
 75%        1.000000      1.000000      0.000000      0.000000      0.000000   
 max        1.000000      1.000000      1.000000      1.000000      1.000000   
 
              size50       size100        sizeno         askd1         askd2  \
 count  50083.000000  50083.000000  50083.000000  50083.000000  50083.000000   
 mean       0.166623      0.166723      0.166743      0.222311      0.222291   
 std        0.372643      0.372732      0.372750      0.415803      0.415790   
 min        0.000000      0.000000      0.000000      0.000000      0.000000   
 25%        0.000000      0.000000      0.000000      0.000000      0.000000   
 50%        0.000000      0.000000      0.000000      0.000000      0.000000   
 75%        0.000000      0.000000      0.000000      0.000000      0.000000   
 max        1.000000      1.000000      1.000000      1.000000      1.000000   
 
        ...        redcty       bluecty        pwhite        pblack  \
 count  ...  49978.000000  49978.000000  48217.000000  48047.000000   
 mean   ...      0.510245      0.488715      0.819599      0.086710   
 std    ...      0.499900      0.499878      0.168560      0.135868   
 min    ...      0.000000      0.000000      0.009418      0.000000   
 25%    ...      0.000000      0.000000      0.755845      0.014729   
 50%    ...      1.000000      0.000000      0.872797      0.036554   
 75%    ...      1.000000      1.000000      0.938827      0.090882   
 max    ...      1.000000      1.000000      1.000000      0.989622   
 
           page18_39     ave_hh_sz  median_hhincome        powner  \
 count  48217.000000  48221.000000     48209.000000  48214.000000   
 mean       0.321694      2.429012     54815.700533      0.669418   
 std        0.103039      0.378105     22027.316665      0.193405   
 min        0.000000      0.000000      5000.000000      0.000000   
 25%        0.258311      2.210000     39181.000000      0.560222   
 50%        0.305534      2.440000     50673.000000      0.712296   
 75%        0.369132      2.660000     66005.000000      0.816798   
 max        0.997544      5.270000    200001.000000      1.000000   
 
        psch_atlstba  pop_propurban  
 count  48215.000000   48217.000000  
 mean       0.391661       0.871968  
 std        0.186599       0.258633  
 min        0.000000       0.000000  
 25%        0.235647       0.884929  
 50%        0.373744       1.000000  
 75%        0.530036       1.000000  
 max        1.000000       1.000000  
 
 [8 rows x 48 columns])</code></pre>
</div>
</div>
<p>The dataset contains 50,083 observations and 51 variables, each representing a prior donor who received a fundraising letter as part of a large-scale field experiment. Each row captures the characteristics of a single solicitation, including the treatment received (e.g., whether a matching grant was offered), attributes of the treatment (such as match ratio and suggested donation amount), and outcomes (e.g., whether the person gave and how much).</p>
<p>The variables span multiple data types, including binary indicators (<code>treatment</code>, <code>control</code>, <code>ratio2</code>, <code>gave</code>), categorical labels (<code>ratio</code>, <code>size</code>, <code>ask</code>), and continuous variables (<code>amount</code>, <code>amountchange</code>, <code>median_hhincome</code>). A subset of the variables describe donor behavior, while others reflect demographic or political attributes of the donor’s region (e.g., <code>pwhite</code>, <code>psch_atlstba</code>, <code>perbush</code>).</p>
<p>Most variables are complete, though a few—such as <code>female</code>, <code>couple</code>, and zip-code-level demographic indicators—contain some missing values. These variables will be useful for subgroup analysis or robustness checks later in the analysis.</p>
<p>Below is a table listing each variable and its definition.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<div id="330df93e" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with missing data in the selected covariates</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> data[[<span class="st">'mrm2'</span>, <span class="st">'years'</span>, <span class="st">'female'</span>, <span class="st">'nonlit'</span>, <span class="st">'treatment'</span>]].dropna()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test for mrm2</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>t_mrm2 <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'mrm2'</span>],</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>, <span class="st">'mrm2'</span>],</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression: mrm2 ~ treatment</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>model_mrm2 <span class="op">=</span> smf.ols(<span class="st">'mrm2 ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeat for 'years'</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>t_years <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'years'</span>],</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>, <span class="st">'years'</span>],</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>model_years <span class="op">=</span> smf.ols(<span class="st">'years ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Female (binary)</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>t_female <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'female'</span>],</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>, <span class="st">'female'</span>],</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>model_female <span class="op">=</span> smf.ols(<span class="st">'female ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Nonlit</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>t_nonlit <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'nonlit'</span>],</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    subset.loc[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>, <span class="st">'nonlit'</span>],</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>model_nonlit <span class="op">=</span> smf.ols(<span class="st">'nonlit ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Output</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"T-Test Results"</span>: {</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mrm2"</span>: t_mrm2,</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>        <span class="st">"years"</span>: t_years,</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>        <span class="st">"female"</span>: t_female,</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>        <span class="st">"nonlit"</span>: t_nonlit</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Regression Coefs (treatment)"</span>: {</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mrm2"</span>: model_mrm2.params[<span class="st">'treatment'</span>],</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>        <span class="st">"years"</span>: model_years.params[<span class="st">'treatment'</span>],</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>        <span class="st">"female"</span>: model_female.params[<span class="st">'treatment'</span>],</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>        <span class="st">"nonlit"</span>: model_nonlit.params[<span class="st">'treatment'</span>]</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Values"</span>: {</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mrm2"</span>: model_mrm2.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>        <span class="st">"years"</span>: model_years.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>        <span class="st">"female"</span>: model_female.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>        <span class="st">"nonlit"</span>: model_nonlit.pvalues[<span class="st">'treatment'</span>]</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>{'T-Test Results': {'mrm2': TtestResult(statistic=0.10979476165416026, pvalue=0.9125728262179356, df=32366.36309248335),
  'years': TtestResult(statistic=-1.0948992897288046, pvalue=0.2735691436031105, df=31455.998443012893),
  'female': TtestResult(statistic=-1.8424593791305501, pvalue=0.06541719238550407, df=32124.51606241337),
  'nonlit': TtestResult(statistic=1.581732537538529, pvalue=0.11372035684297054, df=32552.057508370406)},
 'Regression Coefs (treatment)': {'mrm2': 0.012753705751466927,
  'years': -0.05879664418677571,
  'female': -0.007968707925652073,
  'nonlit': 0.0298005445033021},
 'P-Values': {'mrm2': 0.9125634444738681,
  'years': 0.26837184186459406,
  'female': 0.06463086890487692,
  'nonlit': 0.11445428186637126}}</code></pre>
</div>
</div>
<p>To evaluate whether the randomization successfully produced balanced treatment and control groups, I tested four pre-treatment covariates: <code>mrm2</code> (months since last donation), <code>years</code> (years since initial donation), <code>female</code>, and <code>nonlit</code> (non-litigation activity in state). For each variable, I ran both a two-sample t-test and a simple linear regression with the variable as the outcome and <code>treatment</code> as the independent variable.</p>
<p>The results show no statistically significant differences at the 5% level between treatment and control for any of the covariates. Specifically, p-values from the t-tests were all above 0.05 (<code>mrm2</code>: 0.913, <code>years</code>: 0.274, <code>nonlit</code>: 0.114), except for <code>female</code> which was marginally significant (p = 0.065). These results were confirmed by the corresponding regression analyses.</p>
<p>Taken together, the evidence suggests that the treatment and control groups are well balanced across key pre-treatment variables, supporting the internal validity of the experimental design. This aligns with the findings shown in Table 1 of the original Karlan and List (2007) paper.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div id="3ac3b589" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with missing values in selected covariates</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> data[[<span class="st">'mrm2'</span>, <span class="st">'years'</span>, <span class="st">'female'</span>, <span class="st">'nonlit'</span>, <span class="st">'treatment'</span>]].dropna()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># T-tests</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>t_mrm2 <span class="op">=</span> stats.ttest_ind(subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'mrm2'</span>], subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'mrm2'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>t_years <span class="op">=</span> stats.ttest_ind(subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'years'</span>], subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'years'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>t_female <span class="op">=</span> stats.ttest_ind(subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'female'</span>], subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'female'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>t_nonlit <span class="op">=</span> stats.ttest_ind(subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'nonlit'</span>], subset[subset[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'nonlit'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Regressions</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>model_mrm2 <span class="op">=</span> smf.ols(<span class="st">'mrm2 ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>model_years <span class="op">=</span> smf.ols(<span class="st">'years ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>model_female <span class="op">=</span> smf.ols(<span class="st">'female ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>model_nonlit <span class="op">=</span> smf.ols(<span class="st">'nonlit ~ treatment'</span>, data<span class="op">=</span>subset).fit()</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>results_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Variable'</span>: [<span class="st">'mrm2'</span>, <span class="st">'years'</span>, <span class="st">'female'</span>, <span class="st">'nonlit'</span>],</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'T-test p-value'</span>: [</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        t_mrm2.pvalue,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        t_years.pvalue,</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        t_female.pvalue,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>        t_nonlit.pvalue</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Regression Coef (Treatment)'</span>: [</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        model_mrm2.params[<span class="st">'treatment'</span>],</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>        model_years.params[<span class="st">'treatment'</span>],</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>        model_female.params[<span class="st">'treatment'</span>],</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>        model_nonlit.params[<span class="st">'treatment'</span>]</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Regression p-value'</span>: [</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>        model_mrm2.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>        model_years.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        model_female.pvalues[<span class="st">'treatment'</span>],</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>        model_nonlit.pvalues[<span class="st">'treatment'</span>]</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Round for readability</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>results_table <span class="op">=</span> results_table.<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>results_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">T-test p-value</th>
<th data-quarto-table-cell-role="th">Regression Coef (Treatment)</th>
<th data-quarto-table-cell-role="th">Regression p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>mrm2</td>
<td>0.9126</td>
<td>0.0128</td>
<td>0.9126</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>years</td>
<td>0.2736</td>
<td>-0.0588</td>
<td>0.2684</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>female</td>
<td>0.0654</td>
<td>-0.0080</td>
<td>0.0646</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>nonlit</td>
<td>0.1137</td>
<td>0.0298</td>
<td>0.1145</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To analyze whether matching donations increased the likelihood of giving, I first plotted the share of donors in the treatment and control groups. The barplot clearly shows a higher proportion of individuals donating in the treatment group.</p>
<p>Statistical analysis confirms this difference. A t-test comparing the proportion of donors in each group yields a p-value of 0.0013, indicating the difference is statistically significant. A linear regression of <code>gave</code> on the <code>treatment</code> variable finds a coefficient of 0.0042 (p &lt; 0.01), meaning that being assigned to the matching treatment increased donation likelihood by approximately 0.42 percentage points.</p>
<p>To further confirm the robustness of this finding, I estimated a probit regression where the binary outcome <code>gave</code> was predicted by <code>treatment</code>. The coefficient on <code>treatment</code> was 0.0868 and statistically significant at the 1% level (p = 0.002), replicating the findings in Table 3, Column 1 of Karlan and List (2007).</p>
<p>Taken together, these results indicate that individuals are more likely to give when presented with a matching donation opportunity — even without increasing the match ratio. This supports the hypothesis that perceived amplification of one’s donation can nudge charitable behavior.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<div id="e1fbcc0b" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter only treatment group</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>match_data <span class="op">=</span> data[data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>].copy()</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define groups</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>ratio1 <span class="op">=</span> match_data[(match_data[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (match_data[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">0</span>)]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>ratio2 <span class="op">=</span> match_data[match_data[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>ratio3 <span class="op">=</span> match_data[match_data[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># T-tests</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>t_1v2 <span class="op">=</span> ttest_ind(ratio1[<span class="st">'gave'</span>], ratio2[<span class="st">'gave'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>t_2v3 <span class="op">=</span> ttest_ind(ratio2[<span class="st">'gave'</span>], ratio3[<span class="st">'gave'</span>], equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(t_1v2)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(t_2v3)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Define baseline 1:1 match group</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>match_data[<span class="st">'ratio1'</span>] <span class="op">=</span> ((match_data[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (match_data[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">0</span>)).astype(<span class="bu">int</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression: gave ~ ratio1 + ratio2 + ratio3 (although only two are needed since ratio1 is implied)</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'gave ~ ratio2 + ratio3'</span>, data<span class="op">=</span>match_data).fit()</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>ratio2_effect <span class="op">=</span> model.params[<span class="st">'ratio2'</span>]</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>ratio3_effect <span class="op">=</span> model.params[<span class="st">'ratio3'</span>]</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>diff_2v3 <span class="op">=</span> ratio3_effect <span class="op">-</span> ratio2_effect</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"2:1 vs 1:1 (ratio2 coef)"</span>: ratio2_effect,</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"3:1 vs 2:1 (diff)"</span>: diff_2v3</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=-0.965048975142932, pvalue=0.33453078237183076, df=22225.07770983836)
TtestResult(statistic=-0.05011581369764474, pvalue=0.9600305476940865, df=22260.84918918778)
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gave   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.6454
Date:                Wed, 23 Apr 2025   Prob (F-statistic):              0.524
Time:                        14:09:05   Log-Likelihood:                 16688.
No. Observations:               33396   AIC:                        -3.337e+04
Df Residuals:                   33393   BIC:                        -3.334e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0207      0.001     14.912      0.000       0.018       0.023
ratio2         0.0019      0.002      0.958      0.338      -0.002       0.006
ratio3         0.0020      0.002      1.008      0.313      -0.002       0.006
==============================================================================
Omnibus:                    38963.957   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2506478.937
Skew:                           6.511   Prob(JB):                         0.00
Kurtosis:                      43.394   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>{'2:1 vs 1:1 (ratio2 coef)': 0.0018842510217149957,
 '3:1 vs 2:1 (diff)': 0.00010002398025294552}</code></pre>
</div>
</div>
<p>To evaluate whether larger match ratios increase donation rates, I analyzed only the treatment group and compared response rates across the three match levels: 1:1, 2:1, and 3:1.</p>
<p>I first conducted t-tests between each pair of match conditions: - The comparison between the 1:1 and 2:1 match ratios yielded a p-value of 0.335, indicating no statistically significant difference. - The 2:1 vs 3:1 match comparison also resulted in a non-significant p-value of 0.960.</p>
<p>Next, I regressed the donation indicator <code>gave</code> on the match ratio dummy variables <code>ratio2</code> and <code>ratio3</code>, with 1:1 serving as the baseline category. The regression showed: - A coefficient of <strong>0.0019</strong> for 2:1 (p = 0.338) - A coefficient of <strong>0.0020</strong> for 3:1 (p = 0.313)</p>
<p>These coefficients suggest that while both higher match ratios slightly increased the probability of donating compared to 1:1, <strong>neither effect was statistically significant</strong>.</p>
<p>Finally, I calculated the difference in fitted effects: - 3:1 vs 2:1 match ratio: <strong>0.0001</strong>, again showing virtually no difference.</p>
<p>These findings confirm the authors’ conclusion that while offering a match increases donations, <strong>increasing the match ratio (from 1:1 to 2:1 or 3:1) does not provide additional lift</strong>. This result supports the idea that donors respond to the <em>presence</em> of a match more than to its magnitude.</p>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<div id="3de9b126" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values for 'amount' and 'treatment'</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>subset_all <span class="op">=</span> data[[<span class="st">'amount'</span>, <span class="st">'treatment'</span>]].dropna()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>t_amount_all <span class="op">=</span> ttest_ind(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    subset_all[subset_all[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>],</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    subset_all[subset_all[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>],</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>model_all <span class="op">=</span> smf.ols(<span class="st">'amount ~ treatment'</span>, data<span class="op">=</span>subset_all).fit()</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(t_amount_all)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_all.summary())</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>subset_donors <span class="op">=</span> data[(data[<span class="st">'gave'</span>] <span class="op">==</span> <span class="dv">1</span>)][[<span class="st">'amount'</span>, <span class="st">'treatment'</span>]].dropna()</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>t_amount_donors <span class="op">=</span> ttest_ind(</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>],</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>],</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression: conditional on giving</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>model_donors <span class="op">=</span> smf.ols(<span class="st">'amount ~ treatment'</span>, data<span class="op">=</span>subset_donors).fit()</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(t_amount_donors)</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_donors.summary())</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Means</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>mean_treat <span class="op">=</span> subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>].mean()</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>mean_control <span class="op">=</span> subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>].mean()</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Control group</span></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].hist(subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>], bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(mean_control, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Mean: </span><span class="sc">{</span>mean_control<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Control Group"</span>)</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Donation Amount"</span>)</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Treatment group</span></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].hist(subset_donors[subset_donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>], bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axvline(mean_treat, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Mean: </span><span class="sc">{</span>mean_treat<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Treatment Group"</span>)</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Donation Amount"</span>)</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">"Distribution of Donation Amounts (Among Donors Only)"</span>)</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=1.9182618934467577, pvalue=0.055085665289183336, df=36216.05660774625)
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     3.461
Date:                Wed, 23 Apr 2025   Prob (F-statistic):             0.0628
Time:                        14:09:05   Log-Likelihood:            -1.7946e+05
No. Observations:               50083   AIC:                         3.589e+05
Df Residuals:                   50081   BIC:                         3.589e+05
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.8133      0.067     12.063      0.000       0.681       0.945
treatment      0.1536      0.083      1.861      0.063      -0.008       0.315
==============================================================================
Omnibus:                    96861.113   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        240735713.635
Skew:                          15.297   Prob(JB):                         0.00
Kurtosis:                     341.269   Cond. No.                         3.23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
TtestResult(statistic=-0.5846089794983359, pvalue=0.5590471865673547, df=557.4599304243758)
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 amount   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.3374
Date:                Wed, 23 Apr 2025   Prob (F-statistic):              0.561
Time:                        14:09:05   Log-Likelihood:                -5326.8
No. Observations:                1034   AIC:                         1.066e+04
Df Residuals:                    1032   BIC:                         1.067e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     45.5403      2.423     18.792      0.000      40.785      50.296
treatment     -1.6684      2.872     -0.581      0.561      -7.305       3.968
==============================================================================
Omnibus:                      587.258   Durbin-Watson:                   2.031
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5623.279
Skew:                           2.464   Prob(JB):                         0.00
Kurtosis:                      13.307   Cond. No.                         3.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-6-output-2.png" width="1142" height="473" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To understand how the matching offer influenced donation size, I examined both the unconditional and conditional effects of treatment on donation amount.</p>
</section>
<section id="unconditional-analysis" class="level3">
<h3 class="anchored" data-anchor-id="unconditional-analysis">Unconditional Analysis</h3>
<p>In the full sample (including non-donors), the average donation in the treatment group was slightly higher than in the control group. The regression estimated an increase of $0.15 in donation amount due to treatment, with a p-value of 0.063 — marginally outside conventional thresholds for statistical significance. The corresponding t-test returned a p-value of 0.056. These results suggest that treatment <strong>slightly increases overall donation revenue per solicitation</strong>, though the evidence is only borderline significant.</p>
</section>
<section id="conditional-on-giving" class="level3">
<h3 class="anchored" data-anchor-id="conditional-on-giving">Conditional on Giving</h3>
<p>Restricting the analysis to only those who donated, the story changes. Among donors, the average contribution was <strong>$45.54</strong> in the control group and <strong>$43.87</strong> in the treatment group. The regression coefficient for treatment was -1.67 (p = 0.561), and the t-test similarly showed no significant difference. This implies that <strong>while treatment encourages more people to give, it does not increase how much they give once they decide to donate</strong>.</p>
</section>
<section id="visual-comparison" class="level3">
<h3 class="anchored" data-anchor-id="visual-comparison">Visual Comparison</h3>
<p>The histogram plots for each group show very similar distributions of donation amounts. Both groups are right-skewed, and the means (marked with red dashed lines) are nearly identical. This further supports the conclusion that matching incentives affect donation participation more than donation size.</p>
<p>Overall, these findings reinforce the idea that <strong>the matching offer works by nudging people to give at all</strong>, rather than prompting those already willing to give to give more.</p>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<div id="9a721e68" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 Bernoulli draws for each group</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>control_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.018</span>, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>treatment_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.022</span>, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute difference vector</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>diffs <span class="op">=</span> treatment_draws <span class="op">-</span> control_draws</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Cumulative average of differences</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="op">=</span> np.cumsum(diffs) <span class="op">/</span> np.arange(<span class="dv">1</span>, <span class="bu">len</span>(diffs) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>plt.plot(cumulative_avg, label<span class="op">=</span><span class="st">'Cumulative Average of Differences'</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="fl">0.004</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Mean Difference (0.022 - 0.018)'</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Simulations"</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Cumulative Average Difference"</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Law of Large Numbers: Convergence of Mean Difference"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-7-output-1.png" width="821" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To illustrate the LLN, I simulated 10,000 Bernoulli draws from each distribution and computed the difference in donation outcomes for each simulated pair. Then, I plotted the <strong>cumulative average</strong> of these differences.</p>
<p>The plot shows that although early differences fluctuate, the average steadily converges to the true mean difference (0.004) as the number of observations increases. This mirrors the LLN, which states that sample averages converge to expected values as sample size grows.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<div id="4ce07299" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>true_diff <span class="op">=</span> <span class="fl">0.022</span> <span class="op">-</span> <span class="fl">0.018</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">10</span>))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    diffs <span class="op">=</span> []</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>):</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        control_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.018</span>, size<span class="op">=</span>n)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        treatment_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.022</span>, size<span class="op">=</span>n)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        mean_diff <span class="op">=</span> treatment_sample.mean() <span class="op">-</span> control_sample.mean()</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        diffs.append(mean_diff)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    axes[i].hist(diffs, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'skyblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    axes[i].axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    axes[i].axvline(true_diff, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'True Diff = </span><span class="sc">{</span>true_diff<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    axes[i].set_title(<span class="ss">f'Sample Size: </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    axes[i].legend()</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">"Central Limit Theorem: Sampling Distribution of Mean Differences"</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-8-output-1.png" width="1331" height="945" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To illustrate the CLT, I simulated the difference in average donation outcomes between treatment and control groups across varying sample sizes (n = 50, 200, 500, 1000), repeating the process 1,000 times for each size.</p>
<p>The histograms below show the distribution of these 1,000 average differences. As expected: - Smaller samples (n = 50) produce more <strong>spread-out, irregular</strong> distributions. - Larger samples (n = 1000) produce <strong>narrow, bell-shaped</strong> distributions centered closer to the true difference (0.004).</p>
<p>This highlights that the <strong>sampling distribution of the mean</strong> becomes approximately normal and tighter with larger sample sizes — the core insight behind the CLT. It also justifies the use of t-statistics and confidence intervals in experimental data analysis.</p>
<p>Together, these simulations reinforce why large samples yield more reliable statistical inference.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>